// Embed the public markdown docs into src/static-docs.js so every host (Vercel, Cloudflare Workers, local) serves
// them without filesystem access. Run automatically before tests and deploys (npm run build).
import fs from "node:fs";
const root = new URL("../", import.meta.url);
const files = ["TERMS.md", "OUTREACH.md", "REWARDS.md", "CONTRIBUTING-TOOLS.md"];
const docs = Object.fromEntries(files.map((f) => [f, fs.readFileSync(new URL(f, root), "utf8")]));
const out = `// GENERATED by scripts/build-static.mjs from the markdown files in the repo root. Do not edit.\nexport const DOCS = ${JSON.stringify(docs, null, 0)};\n`;
const target = new URL("src/static-docs.js", root);
if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== out) fs.writeFileSync(target, out);
