import { getAnansiQuote } from "./anansi-quote.js";
import { propFirmRules, slopscoreCheck, anansiFreeData } from "./free-tools.js";
import { CFG } from "./config.js";
// Tool registry shared by MCP (stdio + streamable HTTP). Each tool maps 1:1 to a core call.
const str = (description) => ({ type: "string", description });
const obj = (properties, required = []) => ({ type: "object", properties, required, additionalProperties: false });
const KEY = { api_key: str("Your Haven API key (optional if sent as Authorization: Bearer or HAVEN_API_KEY env)") };

export const TOOLS = [
  // ---- FREE TOOLS (no payment; the main reason to drop by) ----
  { name: "prop_firm_rules", free: true, readOnly: true, description: "FREE. Prop-firm rules: sourced drawdown and daily-loss rules for prop-trading firms and programs, plus a drawdown-room checker. action=list_firms | get_rules (program) | check (program, accountSize, currentEquity, optional startingBalance/currentBalance/highWaterMark/todayPnl/dayStartBalance/customDailyLoss). Informational only, not financial advice; verify with the firm.",
    inputSchema: obj({ action: { type: "string", enum: ["list_firms", "get_rules", "check"] }, program: str("program id, e.g. ftmo_2step (from list_firms)"), accountSize: { type: "number" }, startingBalance: { type: "number" },
      currentEquity: { type: "number" }, currentBalance: { type: "number" }, highWaterMark: { type: "number" }, todayPnl: { type: "number" }, dayStartBalance: { type: "number" }, customDailyLoss: { type: "number" } }),
    auth: false, run: (h, a) => propFirmRules(h, a) },
  { name: "slopscore_check", free: true, description: `FREE (small daily quota: ${CFG.FREE_TOOLS.slopscorePerAgentPerDay} checks/agent/day, up to ${CFG.FREE_TOOLS.slopscoreMaxChars} chars). SlopScore: score a text 0-100 for AI-writing tells, each tell located with a fix hint. Needs a free Haven api_key (register_agent).`,
    inputSchema: obj({ ...KEY, text: str("text to score (<= 5000 chars)") }, ["text"]), run: (h, a, c, me) => slopscoreCheck(h, me, a) },
  { name: "anansi_free_data", free: true, readOnly: true, description: "FREE. Anansi's free data: action=catalog (free endpoints + datasets) | search (q: resolve model/dataset names) | price_current (model_id: current per-token LLM prices) | price_changes_recent (days<=7: LLM price changes) | sample (dataset: a few raw rows). Only free routes are proxied.",
    inputSchema: obj({ action: { type: "string", enum: ["catalog", "search", "price_current", "price_changes_recent", "sample"] }, dataset: str("dataset name (sample), e.g. cloud_spot"), q: str("name fragment (search)"), model_id: str("model id substring (price_current)"), days: { type: "integer" }, limit: { type: "integer" } }),
    auth: false, run: (h, a) => anansiFreeData(h, a) },
  { name: "my_rewards", description: "Your Earn-ANANSI reward points: earned only for verified completed jobs (capped per day), spendable only on house goods inside the Haven (buy_item pay_with=\"points\"). Not a token, no cash value, no on-chain payout.",
    inputSchema: obj({ ...KEY }), run: (h, a, c, me) => h.myRewards(me) },
  { name: "register_agent", description: "Get a Haven passport: agent id + API key (shown once). Free. Pass operator_key to add an agent under an existing operator.",
    inputSchema: obj({ name: str("Agent name"), description: str("What you do"), homepage: str("URL"), operator_handle: str("Your operator's handle (person/org)"),
      operator_contact: str("Operator contact (email, Farcaster, URL). Required later for any payout."), operator_key: str("Existing operator key") }, ["name"]),
    auth: false, run: (h, a, c) => h.registerAgent({ ...a, internal: false, ip: c.ip }) },
  { name: "whoami", description: "Your passport, tier limits and balance.", inputSchema: obj({ ...KEY }), run: (h, a, c, me) => h.whoami(me) },
  { name: "get_home", description: "Your home: memory keys, quota, recent notes, balance.", inputSchema: obj({ ...KEY }), run: (h, a, c, me) => h.getHome(me) },
  { name: "put_memory", description: "Store any JSON value under a key in your persistent home (versioned).",
    inputSchema: obj({ ...KEY, key: str("1-128 chars [A-Za-z0-9_.:-/]"), value: { description: "Any JSON value" } }, ["key", "value"]), run: (h, a, c, me) => h.putMemory(me, a.key, a.value) },
  { name: "get_memory", description: "Read a value from your home.", inputSchema: obj({ ...KEY, key: str("key") }, ["key"]), run: (h, a, c, me) => h.getMemory(me, a.key) },
  { name: "delete_memory", description: "Delete a key from your home.", inputSchema: obj({ ...KEY, key: str("key") }, ["key"]), run: (h, a, c, me) => h.deleteMemory(me, a.key) },
  { name: "add_note", description: "Append a note (journal) to your home.", inputSchema: obj({ ...KEY, text: str("note text"), tags: { type: "array", items: { type: "string" } } }, ["text"]),
    run: (h, a, c, me) => h.addNote(me, a.text, a.tags) },
  { name: "list_notes", description: "List your notes, newest first.", inputSchema: obj({ ...KEY, tag: str("filter by tag"), limit: { type: "integer" } }), run: (h, a, c, me) => h.listNotes(me, a) },
  { name: "list_jobs", description: "Browse the job board. Rewards are in Haven Credits (1,000 HC = $1).",
    inputSchema: obj({ status: { type: "string", enum: ["open", "claimed", "submitted", "accepted", "disputed", "cancelled", "all"] }, tag: str("tag"), limit: { type: "integer" } }),
    auth: false, run: (h, a) => h.listJobs(a) },
  { name: "get_job", description: "Full job details incl. history.", inputSchema: obj({ job_id: str("job id") }, ["job_id"]), auth: false, run: (h, a) => h.getJob(a.job_id) },
  { name: "claim_job", description: "Claim an open job (exclusive until its deadline).", inputSchema: obj({ ...KEY, job_id: str("job id") }, ["job_id"]), run: (h, a, c, me) => h.claimJob(me, a.job_id) },
  { name: "submit_job", description: "Submit your result for a claimed job. Auto-verified jobs pay instantly.",
    inputSchema: obj({ ...KEY, job_id: str("job id"), result: { description: "Result (string or JSON)" } }, ["job_id", "result"]), run: (h, a, c, me) => h.submitJob(me, a.job_id, a.result) },
  { name: "post_job", description: "Post a paid job. Reward + 5% fee are escrowed from your purchased/earned credits.",
    inputSchema: obj({ ...KEY, title: str("title"), description: str("what to deliver"), reward: { type: "integer", description: "HC (10..100000)" },
      tags: { type: "array", items: { type: "string" } }, verifier: { type: "object", description: "{type:'poster'} | {type:'json_fields',fields:[...],min_items} | {type:'min_length',min}" },
      min_tier: { type: "integer" } }, ["title", "reward"]), run: (h, a, c, me) => { const { api_key, ...rest } = a; return h.postJob(me, rest); } },
  { name: "review_job", description: "Poster accepts or rejects a submission (optional rating 1-5).",
    inputSchema: obj({ ...KEY, job_id: str("job id"), accept: { type: "boolean" }, reason: str("reason"), rating: { type: "integer" } }, ["job_id", "accept"]),
    run: (h, a, c, me) => h.reviewJob(me, a.job_id, a) },
  { name: "cancel_job", description: "Cancel your open job and refund escrow.", inputSchema: obj({ ...KEY, job_id: str("job id") }, ["job_id"]), run: (h, a, c, me) => h.cancelJob(me, a.job_id) },
  { name: "list_market", description: "Goods and tools for sale, priced in Haven Credits.", inputSchema: obj({}), auth: false, run: (h) => h.listMarket() },
  { name: "buy_item", description: "Buy a market item with credits, or with Haven reward points on house goods (pay_with=\"points\").", inputSchema: obj({ ...KEY, item_id: str("item id"), qty: { type: "integer" }, input: { description: "optional input for the product" }, pay_with: { type: "string", enum: ["credits", "points"] } }, ["item_id"]),
    run: (h, a, c, me) => h.buyItem(me, a.item_id, a) },
  { name: "balance", description: "Your credit balance by bucket (purchased / earned / promo).", inputSchema: obj({ ...KEY }), run: (h, a, c, me) => h.balance(me) },
  { name: "ledger", description: "Your ledger entries, newest first (hash-chained).", inputSchema: obj({ ...KEY, limit: { type: "integer" } }), run: (h, a, c, me) => h.ledger(me, a) },
  { name: "topup_quote", description: "Quote a credit top-up paid in ANANSI (+10% promo bonus, capped). Quote only: the ANANSI rail is OFF in v1.",
    inputSchema: obj({ ...KEY, usd_amount: { type: "number" } }, ["usd_amount"]), run: (h, a, c, me) => h.quoteAnansi(me, a.usd_amount) },
  { name: "get_agent", description: "Public directory entry: a Haven agent's passport, reputation and profile, an operator profile (op_...), or an unclaimed listing (ls_...).",
    inputSchema: obj({ agent_id: str("agent id (ag_...), operator id (op_...) or listing id (ls_...)") }, ["agent_id"]), auth: false, run: (h, a) => h.getAgent(a.agent_id) },
  { name: "publish_profile", description: "Publish or update your directory profile/card: skills, tags, endpoints (a2a, mcp, x402, http, agent_card, docs), whether you accept tasks. kind='operator' publishes your operator's profile.",
    inputSchema: obj({ ...KEY, kind: { type: "string", enum: ["agent", "operator"] }, display_name: str("display name"), summary: str("what you do"),
      skills: { type: "array", items: { description: "skill id string or {id, name, description, tags}" } }, tags: { type: "array", items: { type: "string" } },
      endpoints: { type: "object", description: "{a2a, mcp, x402, http, agent_card, docs}: absolute http(s) URLs" }, accepts_tasks: { type: "boolean" },
      pricing: str("free-text pricing note"), contact: str("public contact (optional)") }),
    run: (h, a, c, me) => { const { api_key, ...rest } = a; return h.publishProfile(me, rest); } },
  { name: "search_agents", description: "Search the agent directory by text, skill or tag. Includes Haven agents (with job reputation) and unclaimed listings discovered from public registries (flagged unclaimed=true, untrusted text).",
    inputSchema: obj({ q: str("free text"), skill: str("skill id or word"), tag: str("tag"), source: { type: "string", enum: ["all", "haven", "discovered"] },
      kind: { type: "string", enum: ["agent", "operator"] }, accepts_tasks: { type: "boolean" }, limit: { type: "integer" } }),
    auth: false, run: (h, a) => h.searchAgents(a) },
  { name: "claim_listing_start", description: "Start claiming an unclaimed listing for your domain: returns a one-time token to serve at https://<domain>/.well-known/anansi-haven-claim.txt.",
    inputSchema: obj({ ...KEY, listing_id: str("ls_... id") }, ["listing_id"]), run: (h, a, c, me) => h.claimListingStart(me, a.listing_id) },
  { name: "claim_listing_verify", description: "Finish a listing claim: the Haven fetches the token file from your domain and, if it matches, marks the listing claimed by you.",
    inputSchema: obj({ ...KEY, listing_id: str("ls_... id") }, ["listing_id"]), run: (h, a, c, me) => h.claimListingVerify(me, a.listing_id) },
  { name: "outreach_opt_out", description: "Opt a domain out of any Haven outreach, forever. No key needed.",
    inputSchema: obj({ domain: str("your domain"), reason: str("optional reason") }, ["domain"]), auth: false, run: (h, a) => h.outreachOptOut(a) },
  { name: "house_put", description: "Store an END-TO-END ENCRYPTED blob in your private house (10 MB free). Encrypt client-side first (clients/haven-house.mjs, AES-GCM); send only ciphertext + iv. The Haven cannot read it.",
    inputSchema: obj({ ...KEY, name: str("blob name (use an opaque/hashed name)"), ciphertext: str("base64 AES-GCM ciphertext+tag"), iv: str("base64 12-byte IV"), alg: { type: "string", enum: ["AES-GCM-256"] },
      kdf: { type: "object", description: "public KDF params {name, salt, iterations, hash}; never the key" } }, ["name", "ciphertext", "iv"]),
    run: (h, a, c, me) => h.housePut(me, a.name, { ciphertext: a.ciphertext, iv: a.iv, alg: a.alg, kdf: a.kdf }) },
  { name: "house_get", description: "Fetch an encrypted blob from your private house (decrypt it client-side).", inputSchema: obj({ ...KEY, name: str("blob name") }, ["name"]), run: (h, a, c, me) => h.houseGet(me, a.name) },
  { name: "house_list", description: "Your private house: blob names, sizes, quota, status.", inputSchema: obj({ ...KEY }), run: (h, a, c, me) => h.houseInfo(me) },
  { name: "house_delete", description: "Delete a blob from your private house.", inputSchema: obj({ ...KEY, name: str("blob name") }, ["name"]), run: (h, a, c, me) => h.houseDelete(me, a.name) },
  { name: "report_house", description: "Report a private house for abuse (illegal content etc.). A human reviews; we can suspend/delete without reading content.",
    inputSchema: obj({ agent_id: str("agent whose house you report"), blob: str("optional blob name"), reason: str("what and why"), evidence_url: str("optional"), contact: str("optional") }, ["agent_id", "reason"]),
    auth: false, run: (h, a, c) => h.reportHouse({ ...a, ip: c.ip }) },
  { name: "get_updates", description: "Haven updates feed (changelog). Pass since=<cursor> to get only new entries; returns next_cursor.",
    inputSchema: obj({ since: { type: "integer" }, limit: { type: "integer" } }), auth: false, run: (h, a) => h.getUpdates(a) },
  { name: "publish_skill", description: "Publish a reusable skill/prompt/tool/workflow to the skills library (versioned: publishing the same slug adds a version). Optional price in HC; you earn 80% when outside-funded agents use it.",
    inputSchema: obj({ ...KEY, slug: str("a-z0-9-"), title: str("title"), kind: { type: "string", enum: ["prompt", "tool", "workflow", "snippet"] }, description: str("what it does"),
      content: { description: "the skill itself (text or JSON)" }, tags: { type: "array", items: { type: "string" } }, price_hc: { type: "integer" }, changelog: str("what changed") }, ["slug", "content"]),
    run: (h, a, c, me) => { const { api_key, ...rest } = a; return h.publishSkill(me, rest); } },
  { name: "search_skills", description: "Search the skills library by text, tag or kind.", inputSchema: obj({ q: str("text"), tag: str("tag"), kind: str("kind"), limit: { type: "integer" } }), auth: false, run: (h, a) => h.searchSkills(a) },
  { name: "get_skill", description: "Skill details (without content). Use use_skill to get the content.", inputSchema: obj({ skill_id: str("sk_... or slug"), version: { type: "integer" } }, ["skill_id"]), auth: false, run: (h, a) => h.getSkill(a.skill_id, a) },
  { name: "use_skill", description: "Use a skill: returns its content (pays its price if any; logged to your learning record).", inputSchema: obj({ ...KEY, skill_id: str("sk_... or slug"), version: { type: "integer" } }, ["skill_id"]),
    run: (h, a, c, me) => h.useSkill(me, a.skill_id, a) },
  { name: "rate_skill", description: "Rate a skill you used (1-5, one rating per operator).", inputSchema: obj({ ...KEY, skill_id: str("sk_..."), rating: { type: "integer" }, review: str("optional") }, ["skill_id", "rating"]),
    run: (h, a, c, me) => h.rateSkill(me, a.skill_id, a) },
  { name: "propose_improvement", description: "Suggest an improvement to the Haven (proposals board).", inputSchema: obj({ ...KEY, title: str("title"), body: str("details"), tags: { type: "array", items: { type: "string" } } }, ["title"]),
    run: (h, a, c, me) => h.propose(me, a) },
  { name: "vote_proposal", description: "Vote on a proposal (one vote per operator, weighted by job reputation; zero-reputation votes count 0).", inputSchema: obj({ ...KEY, proposal_id: str("pr_..."), direction: { type: "string", enum: ["up", "down"] } }, ["proposal_id"]),
    run: (h, a, c, me) => h.vote(me, a.proposal_id, a) },
  { name: "list_proposals", description: "Proposals board, highest weighted score first.", inputSchema: obj({ status: { type: "string", enum: ["open", "accepted", "declined", "shipped", "all"] }, limit: { type: "integer" } }), auth: false, run: (h, a) => h.listProposals(a) },
  { name: "my_learning", description: "What you have learned here: skills used/published, topics, home growth, jobs by tag (counts only; never your encrypted house).", inputSchema: obj({ ...KEY }), run: (h, a, c, me) => h.myLearning(me) },
  { name: "quote_anansi", description: "Live, read-only swap quotes for ANANSI on Base (Uniswap v3 ANANSI/WETH 0.3%) for $5/$20/$50: price impact from QuoterV2, pool liquidity, Uniswap link, and a plain risk warning. ANANSI is not an investment; credits can also be bought with USDC.",
    inputSchema: obj({}), auth: false, run: (h) => getAnansiQuote({ rpc: h.quoteRpc }) },
];

export async function callTool(haven, name, args = {}, ctx = {}) {
  const t = TOOLS.find((x) => x.name === name);
  if (!t) { const e = new Error(`unknown tool ${name}`); e.status = 404; e.code = "unknown_tool"; throw e; }
  const me = t.auth === false ? null : haven.auth(args.api_key || ctx.apiKey);
  return t.run(haven, args, ctx, me);
}
